import type { ChallengeSet } from "../types";

export const changeSet: ChallengeSet = {
  mode: "c",
  label: "Change",
  description: "Practice the c operator with motions and text objects",
  key: "c",
  challenges: [
    {
      id: "c-cw-1",
      mode: "c",
      prompt: "Change the word under the cursor to 'world'",
      initialContent: 'const greeting = "hello";',
      cursorPos: 19,
      expectedContent: 'const greeting = "world";',
      expectedCursorPos: 24,
      expectedCommand: "cwworld",
      tags: ["change", "word"],
      difficulty: 1,
    },
    {
      id: "c-ciw-1",
      mode: "c",
      prompt: "Change the entire word under the cursor to 'count'",
      initialContent: "let value = 42;",
      cursorPos: 6,
      expectedContent: "let count = 42;",
      expectedCursorPos: 9,
      expectedCommand: "ciwcount",
      tags: ["change", "inner-word"],
      difficulty: 1,
    },
    {
      id: "c-ci-quote-1",
      mode: "c",
      prompt: "Change the text inside the double quotes to 'goodbye'",
      initialContent: 'console.log("hello world");',
      cursorPos: 14,
      expectedContent: 'console.log("goodbye");',
      expectedCursorPos: 20,
      expectedCommand: 'ci"goodbye',
      tags: ["change", "inner-quotes"],
      difficulty: 1,
    },
    {
      id: "c-ci-paren-1",
      mode: "c",
      prompt: "Change the text inside the parentheses to 'x, y'",
      initialContent: "function add(a, b) {",
      cursorPos: 14,
      expectedContent: "function add(x, y) {",
      expectedCursorPos: 17,
      expectedCommand: "ci(x, y",
      tags: ["change", "inner-paren"],
      difficulty: 1,
    },
    {
      id: "c-c$-1",
      mode: "c",
      prompt: "Change from cursor to end of line to ' = 0;'",
      initialContent: "let counter = 100;",
      cursorPos: 11,
      expectedContent: "let counter = 0;",
      expectedCursorPos: 16,
      expectedCommand: "c$ = 0;",
      tags: ["change", "end-of-line"],
      difficulty: 1,
    },
    {
      id: "c-cb-1",
      mode: "c",
      prompt: "Change backwards to the start of the word, replacing with 'max'",
      initialContent: "const minValue = 5;",
      cursorPos: 8,
      expectedContent: "const maxValue = 5;",
      expectedCursorPos: 9,
      expectedCommand: "cbmax",
      tags: ["change", "back-word"],
      difficulty: 2,
    },
    {
      id: "c-cc-1",
      mode: "c",
      prompt: "Change the entire line to '  return null;'",
      initialContent: "  return undefined;",
      cursorPos: 9,
      expectedContent: "  return null;",
      expectedCursorPos: 14,
      expectedCommand: "ccreturn null;",
      alternativeCommands: ["Sreturn null;"],
      tags: ["change", "line"],
      difficulty: 1,
    },
    {
      id: "c-ci-bracket-1",
      mode: "c",
      prompt: "Change the text inside the curly braces to ' done: true '",
      initialContent: "const obj = { loading: false };",
      cursorPos: 18,
      expectedContent: "const obj = { done: true };",
      expectedCursorPos: 26,
      expectedCommand: "ci{ done: true ",
      tags: ["change", "inner-brace"],
      difficulty: 2,
    },
    {
      id: "c-ci-sq-1",
      mode: "c",
      prompt: "Change the text inside the square brackets to '0'",
      initialContent: "const first = items[index];",
      cursorPos: 21,
      expectedContent: "const first = items[0];",
      expectedCursorPos: 21,
      expectedCommand: "ci[0",
      tags: ["change", "inner-bracket"],
      difficulty: 2,
    },
    {
      id: "c-ca-quote-1",
      mode: "c",
      prompt: "Change the text including the quotes to 'null'",
      initialContent: 'const name = "Alice";',
      cursorPos: 15,
      expectedContent: "const name = null;",
      expectedCursorPos: 17,
      expectedCommand: 'ca"null',
      tags: ["change", "around-quotes"],
      difficulty: 2,
    },
    {
      id: "c-ce-1",
      mode: "c",
      prompt: "Change to the end of the word, replacing with 'items'",
      initialContent: "const elements = [];",
      cursorPos: 6,
      expectedContent: "const items = [];",
      expectedCursorPos: 11,
      expectedCommand: "ceitems",
      tags: ["change", "end-word"],
      difficulty: 1,
    },
    {
      id: "c-cf-1",
      mode: "c",
      prompt: "Change from cursor up to and including '=' to 'total ='",
      initialContent: "const sum = 0;",
      cursorPos: 6,
      expectedContent: "const total = 0;",
      expectedCursorPos: 13,
      expectedCommand: "cf=total =",
      tags: ["change", "find"],
      difficulty: 3,
    },
    {
      id: "c-ct-1",
      mode: "c",
      prompt: "Change from cursor up to (not including) '(' to 'getData'",
      initialContent: "  fetchUsers(id);",
      cursorPos: 2,
      expectedContent: "  getData(id);",
      expectedCursorPos: 9,
      expectedCommand: "ct(getData",
      tags: ["change", "till"],
      difficulty: 3,
    },
    {
      id: "c-c2w-1",
      mode: "c",
      prompt: "Change the next 2 words to 'isValid'",
      initialContent: "if (has_error) return;",
      cursorPos: 4,
      expectedContent: "if (isValid) return;",
      expectedCursorPos: 11,
      expectedCommand: "c2wisValid",
      tags: ["change", "count", "word"],
      difficulty: 2,
    },
    {
      id: "c-ci-tick-1",
      mode: "c",
      prompt: "Change the text inside the backticks to 'world'",
      initialContent: "const msg = `hello`;",
      cursorPos: 14,
      expectedContent: "const msg = `world`;",
      expectedCursorPos: 18,
      expectedCommand: "ci`world",
      tags: ["change", "inner-backtick"],
      difficulty: 2,
    },
  ],
};
