import type { ChallengeSet } from "../types";

export const deleteSet: ChallengeSet = {
  mode: "d",
  label: "Delete",
  description: "Practice the d operator with motions and text objects",
  key: "d",
  challenges: [
    {
      id: "d-dw-1",
      mode: "d",
      prompt: "Delete the word under the cursor",
      initialContent: "const old value = 5;",
      cursorPos: 6,
      expectedContent: "const value = 5;",
      expectedCursorPos: 6,
      expectedCommand: "dw",
      tags: ["delete", "word"],
      difficulty: 1,
    },
    {
      id: "d-diw-1",
      mode: "d",
      prompt: "Delete the entire word under the cursor",
      initialContent: "remove this word here",
      cursorPos: 9,
      expectedContent: "remove  word here",
      expectedCursorPos: 7,
      expectedCommand: "diw",
      tags: ["delete", "inner-word"],
      difficulty: 1,
    },
    {
      id: "d-dd-1",
      mode: "d",
      prompt: "Delete the entire line",
      initialContent: "line one\ndelete me\nline three",
      cursorPos: 9,
      expectedContent: "line one\nline three",
      expectedCursorPos: 9,
      expectedCommand: "dd",
      tags: ["delete", "line"],
      difficulty: 1,
    },
    {
      id: "d-d$-1",
      mode: "d",
      prompt: "Delete from cursor to end of line",
      initialContent: "keep this remove this",
      cursorPos: 10,
      expectedContent: "keep this ",
      expectedCursorPos: 9,
      expectedCommand: "d$",
      alternativeCommands: ["D"],
      tags: ["delete", "end-of-line"],
      difficulty: 1,
    },
    {
      id: "d-d0-1",
      mode: "d",
      prompt: "Delete from cursor to start of line",
      initialContent: "delete this keep",
      cursorPos: 12,
      expectedContent: "keep",
      expectedCursorPos: 0,
      expectedCommand: "d0",
      tags: ["delete", "start-of-line"],
      difficulty: 1,
    },
    {
      id: "d-di-quote-1",
      mode: "d",
      prompt: "Delete the text inside the double quotes",
      initialContent: 'let msg = "hello world";',
      cursorPos: 14,
      expectedContent: 'let msg = "";',
      expectedCursorPos: 11,
      expectedCommand: 'di"',
      tags: ["delete", "inner-quotes"],
      difficulty: 1,
    },
    {
      id: "d-da-paren-1",
      mode: "d",
      prompt: "Delete the parentheses and everything inside them",
      initialContent: "calculate(a + b) + rest",
      cursorPos: 11,
      expectedContent: "calculate + rest",
      expectedCursorPos: 9,
      expectedCommand: "da(",
      alternativeCommands: ["da)"],
      tags: ["delete", "around-paren"],
      difficulty: 2,
    },
    {
      id: "d-dt-1",
      mode: "d",
      prompt: "Delete from cursor up to (not including) the semicolon",
      initialContent: "let x = 42;",
      cursorPos: 4,
      expectedContent: "let ;",
      expectedCursorPos: 4,
      expectedCommand: "dt;",
      tags: ["delete", "till"],
      difficulty: 2,
    },
    {
      id: "d-df-1",
      mode: "d",
      prompt: "Delete from cursor up to and including the comma",
      initialContent: "first, second, third",
      cursorPos: 0,
      expectedContent: " second, third",
      expectedCursorPos: 0,
      expectedCommand: "df,",
      tags: ["delete", "find"],
      difficulty: 2,
    },
    {
      id: "d-daw-1",
      mode: "d",
      prompt: "Delete the word under the cursor including surrounding space",
      initialContent: "one two three",
      cursorPos: 5,
      expectedContent: "one three",
      expectedCursorPos: 4,
      expectedCommand: "daw",
      tags: ["delete", "around-word"],
      difficulty: 2,
    },
    {
      id: "d-di-brace-1",
      mode: "d",
      prompt: "Delete the text inside the curly braces",
      initialContent: "if (true) { return 1; }",
      cursorPos: 15,
      expectedContent: "if (true) {}",
      expectedCursorPos: 11,
      expectedCommand: "di{",
      alternativeCommands: ["di}"],
      tags: ["delete", "inner-brace"],
      difficulty: 2,
    },
    {
      id: "d-d2w-1",
      mode: "d",
      prompt: "Delete the next 2 words",
      initialContent: "remove these two words",
      cursorPos: 7,
      expectedContent: "remove words",
      expectedCursorPos: 7,
      expectedCommand: "d2w",
      tags: ["delete", "count", "word"],
      difficulty: 2,
    },
  ],
};
