import type { ChallengeSet } from "../types";

export const findSet: ChallengeSet = {
  mode: "find",
  label: "Find",
  description: "Practice f, t, F, T character search motions",
  key: "f",
  challenges: [
    {
      id: "f-fa-1",
      mode: "find",
      prompt: "Jump to the next 'a' character",
      initialContent: "find the letter a here",
      cursorPos: 0,
      expectedContent: "find the letter a here",
      expectedCursorPos: 16,
      expectedCommand: "fa",
      tags: ["find", "forward"],
      difficulty: 1,
    },
    {
      id: "f-f-comma-1",
      mode: "find",
      prompt: "Jump to the next comma",
      initialContent: "alpha, beta, gamma",
      cursorPos: 0,
      expectedContent: "alpha, beta, gamma",
      expectedCursorPos: 5,
      expectedCommand: "f,",
      tags: ["find", "forward"],
      difficulty: 1,
    },
    {
      id: "f-t-paren-1",
      mode: "find",
      prompt: "Jump to just before the opening parenthesis",
      initialContent: "return getValue(x);",
      cursorPos: 0,
      expectedContent: "return getValue(x);",
      expectedCursorPos: 14,
      expectedCommand: "t(",
      tags: ["find", "till"],
      difficulty: 1,
    },
    {
      id: "f-F-1",
      mode: "find",
      prompt: "Jump backward to the previous '=' character",
      initialContent: "const x = y = 5;",
      cursorPos: 14,
      expectedContent: "const x = y = 5;",
      expectedCursorPos: 12,
      expectedCommand: "F=",
      tags: ["find", "backward"],
      difficulty: 2,
    },
    {
      id: "f-T-1",
      mode: "find",
      prompt: "Jump backward to just after the previous '.'",
      initialContent: "obj.method.call()",
      cursorPos: 15,
      expectedContent: "obj.method.call()",
      expectedCursorPos: 11,
      expectedCommand: "T.",
      tags: ["find", "backward-till"],
      difficulty: 2,
    },
    {
      id: "f-df-1",
      mode: "find",
      prompt: "Delete from cursor up to and including the next ')'",
      initialContent: "func(old) + rest",
      cursorPos: 4,
      expectedContent: "func + rest",
      expectedCursorPos: 4,
      expectedCommand: "df)",
      tags: ["find", "delete"],
      difficulty: 2,
    },
    {
      id: "f-ct-1",
      mode: "find",
      prompt: "Change from cursor to just before ':' to 'name'",
      initialContent: '  key: "value",',
      cursorPos: 2,
      expectedContent: '  name: "value",',
      expectedCursorPos: 6,
      expectedCommand: "ct:name",
      tags: ["find", "change", "till"],
      difficulty: 3,
    },
    {
      id: "f-f-semi-1",
      mode: "find",
      prompt: "Jump to the semicolon",
      initialContent: "let x = 0; let y = 1;",
      cursorPos: 0,
      expectedContent: "let x = 0; let y = 1;",
      expectedCursorPos: 9,
      expectedCommand: "f;",
      tags: ["find", "forward"],
      difficulty: 1,
    },
    {
      id: "f-2f-1",
      mode: "find",
      prompt: "Jump to the second '/' character",
      initialContent: "https://example.com/path",
      cursorPos: 0,
      expectedContent: "https://example.com/path",
      expectedCursorPos: 7,
      expectedCommand: "2f/",
      tags: ["find", "count"],
      difficulty: 3,
    },
    {
      id: "f-dt-1",
      mode: "find",
      prompt: "Delete from cursor up to (not including) the space",
      initialContent: "longprefix value",
      cursorPos: 0,
      expectedContent: " value",
      expectedCursorPos: 0,
      expectedCommand: "dt ",
      tags: ["find", "delete", "till"],
      difficulty: 2,
    },
  ],
};
