import type { ChallengeSet } from "../types";

export const fixSet: ChallengeSet = {
  mode: "fix",
  label: "Fix",
  description: "Typo fixes, character replacements, and quick corrections",
  key: "!",
  challenges: [
    {
      id: "fix-replace-char-1",
      mode: "fix",
      prompt: "Fix the typo: replace 'z' with 's'",
      initialContent: "conzt x = 1;",
      cursorPos: 3,
      expectedContent: "const x = 1;",
      expectedCursorPos: 3,
      expectedCommand: "rs",
      tags: ["fix", "replace"],
      difficulty: 1,
    },
    {
      id: "fix-replace-char-2",
      mode: "fix",
      prompt: "Fix the typo: replace '0' with 'o'",
      initialContent: "c0nst x = 1;",
      cursorPos: 1,
      expectedContent: "const x = 1;",
      expectedCursorPos: 1,
      expectedCommand: "ro",
      tags: ["fix", "replace"],
      difficulty: 1,
    },
    {
      id: "fix-delete-extra",
      mode: "fix",
      prompt: "Delete the extra character to fix 'consst'",
      initialContent: "consst x = 1;",
      cursorPos: 4,
      expectedContent: "const x = 1;",
      expectedCursorPos: 4,
      expectedCommand: "x",
      tags: ["fix", "delete"],
      difficulty: 1,
    },
    {
      id: "fix-delete-extra-equals",
      mode: "fix",
      prompt: "Delete the extra '=' to fix the assignment",
      initialContent: "let x == 1;",
      cursorPos: 6,
      expectedContent: "let x = 1;",
      expectedCursorPos: 6,
      expectedCommand: "x",
      tags: ["fix", "delete"],
      difficulty: 1,
    },
    {
      id: "fix-missing-paren",
      mode: "fix",
      prompt: "Add the missing closing parenthesis",
      initialContent: 'console.log("hello"',
      cursorPos: 0,
      expectedContent: 'console.log("hello")',
      expectedCursorPos: 19,
      expectedCommand: "A)",
      tags: ["fix", "append"],
      difficulty: 1,
    },
    {
      id: "fix-wrong-bracket",
      mode: "fix",
      prompt: "Replace the ( with { to fix the block",
      initialContent: "if (true) (",
      cursorPos: 10,
      expectedContent: "if (true) {",
      expectedCursorPos: 10,
      expectedCommand: "r{",
      tags: ["fix", "replace"],
      difficulty: 1,
    },
    {
      id: "fix-missing-colon",
      mode: "fix",
      prompt: "Add the missing colon after the key",
      initialContent: '  name "Alice"',
      cursorPos: 6,
      expectedContent: '  name: "Alice"',
      expectedCursorPos: 6,
      expectedCommand: "i:",
      tags: ["fix", "insert"],
      difficulty: 1,
    },
    {
      id: "fix-wrong-string",
      mode: "fix",
      prompt: "Change 'false' to 'true'",
      initialContent: "const enabled = false;",
      cursorPos: 16,
      expectedContent: "const enabled = true;",
      expectedCursorPos: 20,
      expectedCommand: "ciwtrue",
      tags: ["fix", "rename"],
      difficulty: 1,
    },
    {
      id: "fix-semicolon-to-comma",
      mode: "fix",
      prompt: "Replace the semicolon with a comma",
      initialContent: "const a = 1; b = 2;",
      cursorPos: 11,
      expectedContent: "const a = 1, b = 2;",
      expectedCursorPos: 11,
      expectedCommand: "r,",
      tags: ["fix", "replace"],
      difficulty: 1,
    },
    {
      id: "fix-missing-return",
      mode: "fix",
      prompt: "Add 'return ' before the expression",
      initialContent: "  x + 1;",
      cursorPos: 2,
      expectedContent: "  return x + 1;",
      expectedCursorPos: 8,
      expectedCommand: "ireturn ",
      alternativeCommands: ["Ireturn "],
      tags: ["fix", "insert"],
      difficulty: 2,
    },
  ],
};
