import type { ChallengeSet } from "../types";

export const formatSet: ChallengeSet = {
  mode: "format",
  label: "Format",
  description: "Indent, join, case changes, and code formatting",
  key: "=",
  challenges: [
    {
      id: "fmt-join-1",
      mode: "format",
      prompt: "Join the next line to this one",
      initialContent: "const x =\n  1;",
      cursorPos: 0,
      expectedContent: "const x = 1;",
      expectedCursorPos: 9,
      expectedCommand: "J",
      tags: ["format", "join"],
      difficulty: 1,
    },
    {
      id: "fmt-join-2",
      mode: "format",
      prompt: "Join all three lines into one",
      initialContent: "a,\nb,\nc",
      cursorPos: 0,
      expectedContent: "a, b, c",
      expectedCursorPos: 5,
      expectedCommand: "3J",
      tags: ["format", "join", "count"],
      difficulty: 2,
    },
    {
      id: "fmt-upper-word",
      mode: "format",
      prompt: "Uppercase the word under the cursor",
      initialContent: 'const name = "hello";',
      cursorPos: 14,
      expectedContent: 'const name = "HELLO";',
      expectedCursorPos: 14,
      expectedCommand: "gUiw",
      tags: ["format", "case"],
      difficulty: 2,
    },
    {
      id: "fmt-lower-word",
      mode: "format",
      prompt: "Lowercase the word under the cursor",
      initialContent: "const NAME = 42;",
      cursorPos: 6,
      expectedContent: "const name = 42;",
      expectedCursorPos: 6,
      expectedCommand: "guiw",
      tags: ["format", "case"],
      difficulty: 2,
    },
    {
      id: "fmt-semicolon",
      mode: "format",
      prompt: "Add a semicolon at the end of the line",
      initialContent: "const x = 1",
      cursorPos: 0,
      expectedContent: "const x = 1;",
      expectedCursorPos: 11,
      expectedCommand: "A;",
      tags: ["format", "append"],
      difficulty: 1,
    },
    {
      id: "fmt-comment-line",
      mode: "format",
      prompt: "Comment out this line with //",
      initialContent: "const x = 1;",
      cursorPos: 5,
      expectedContent: "// const x = 1;",
      expectedCursorPos: 2,
      expectedCommand: "I// ",
      tags: ["format", "comment"],
      difficulty: 2,
    },
    {
      id: "fmt-delete-blank",
      mode: "format",
      prompt: "Delete the empty line in the middle",
      initialContent: "const a = 1;\n\nconst b = 2;",
      cursorPos: 0,
      expectedContent: "const a = 1;\nconst b = 2;",
      expectedCursorPos: 13,
      expectedCommand: "jdd",
      tags: ["format", "delete-line"],
      difficulty: 1,
    },
    {
      id: "fmt-upper-all",
      mode: "format",
      prompt: "Uppercase the entire word 'error' to 'ERROR'",
      initialContent: "throw new error();",
      cursorPos: 10,
      expectedContent: "throw new ERROR();",
      expectedCursorPos: 10,
      expectedCommand: "gUiw",
      alternativeCommands: ["gUe"],
      tags: ["format", "case"],
      difficulty: 2,
    },
    {
      id: "fmt-append-bracket",
      mode: "format",
      prompt: "Add the missing closing curly brace at the end",
      initialContent: "if (true) {",
      cursorPos: 0,
      expectedContent: "if (true) {}",
      expectedCursorPos: 11,
      expectedCommand: "A}",
      tags: ["format", "append"],
      difficulty: 1,
    },
  ],
};
