import type { ChallengeSet } from "../types";

export const motionSet: ChallengeSet = {
  mode: "motion",
  label: "Motions",
  description: "Practice cursor movement with w, b, e, 0, $, and more",
  key: "w",
  challenges: [
    {
      id: "m-w-1",
      mode: "motion",
      prompt: "Move to the next word",
      initialContent: "const value = 42;",
      cursorPos: 0,
      expectedContent: "const value = 42;",
      expectedCursorPos: 6,
      expectedCommand: "w",
      tags: ["motion", "word"],
      difficulty: 1,
    },
    {
      id: "m-b-1",
      mode: "motion",
      prompt: "Move to the previous word",
      initialContent: "const value = 42;",
      cursorPos: 14,
      expectedContent: "const value = 42;",
      expectedCursorPos: 12,
      expectedCommand: "b",
      tags: ["motion", "back"],
      difficulty: 1,
    },
    {
      id: "m-e-1",
      mode: "motion",
      prompt: "Move to the end of the current word",
      initialContent: "hello world",
      cursorPos: 0,
      expectedContent: "hello world",
      expectedCursorPos: 4,
      expectedCommand: "e",
      tags: ["motion", "end"],
      difficulty: 1,
    },
    {
      id: "m-0-1",
      mode: "motion",
      prompt: "Move to the start of the line",
      initialContent: "  some indented text",
      cursorPos: 12,
      expectedContent: "  some indented text",
      expectedCursorPos: 0,
      expectedCommand: "0",
      tags: ["motion", "line-start"],
      difficulty: 1,
    },
    {
      id: "m-$-1",
      mode: "motion",
      prompt: "Move to the end of the line",
      initialContent: "go to the end",
      cursorPos: 3,
      expectedContent: "go to the end",
      expectedCursorPos: 12,
      expectedCommand: "$",
      tags: ["motion", "line-end"],
      difficulty: 1,
    },
    {
      id: "m-2w-1",
      mode: "motion",
      prompt: "Move forward 2 words",
      initialContent: "one two three four",
      cursorPos: 0,
      expectedContent: "one two three four",
      expectedCursorPos: 8,
      expectedCommand: "2w",
      tags: ["motion", "count", "word"],
      difficulty: 2,
    },
    {
      id: "m-fx-1",
      mode: "motion",
      prompt: "Jump to the next '=' character",
      initialContent: "const x = 10;",
      cursorPos: 0,
      expectedContent: "const x = 10;",
      expectedCursorPos: 8,
      expectedCommand: "f=",
      tags: ["motion", "find"],
      difficulty: 2,
    },
    {
      id: "m-tx-1",
      mode: "motion",
      prompt: "Jump to just before the '(' character",
      initialContent: "  callFunction(args);",
      cursorPos: 2,
      expectedContent: "  callFunction(args);",
      expectedCursorPos: 13,
      expectedCommand: "t(",
      tags: ["motion", "till"],
      difficulty: 2,
    },
    {
      id: "m-gg-1",
      mode: "motion",
      prompt: "Jump to the first line of the file",
      initialContent: "line one\nline two\nline three",
      cursorPos: 18,
      expectedContent: "line one\nline two\nline three",
      expectedCursorPos: 0,
      expectedCommand: "gg",
      tags: ["motion", "file"],
      difficulty: 1,
    },
    {
      id: "m-G-1",
      mode: "motion",
      prompt: "Jump to the last line of the file",
      initialContent: "line one\nline two\nline three",
      cursorPos: 0,
      expectedContent: "line one\nline two\nline three",
      expectedCursorPos: 18,
      expectedCommand: "G",
      tags: ["motion", "file"],
      difficulty: 1,
    },
    {
      id: "m-3b-1",
      mode: "motion",
      prompt: "Move back 3 words",
      initialContent: "alpha beta gamma delta",
      cursorPos: 17,
      expectedContent: "alpha beta gamma delta",
      expectedCursorPos: 6,
      expectedCommand: "3b",
      tags: ["motion", "count", "back"],
      difficulty: 2,
    },
    {
      id: "m-caret-1",
      mode: "motion",
      prompt: "Move to the first non-blank character of the line",
      initialContent: "    indented code",
      cursorPos: 0,
      expectedContent: "    indented code",
      expectedCursorPos: 4,
      expectedCommand: "^",
      tags: ["motion", "soft-bol"],
      difficulty: 1,
    },
  ],
};
