import type { ChallengeSet } from "../types";

export const refactorSet: ChallengeSet = {
  mode: "refactor",
  label: "Refactor",
  description: "Rename, move, swap, and duplicate — real editing patterns",
  key: "r",
  challenges: [
    {
      id: "ref-rename-1",
      mode: "refactor",
      prompt: "Change the variable name 'tmp' to 'result'",
      initialContent: "let tmp = getValue();",
      cursorPos: 4,
      expectedContent: "let result = getValue();",
      expectedCursorPos: 10,
      expectedCommand: "ciwresult",
      tags: ["refactor", "rename"],
      difficulty: 1,
    },
    {
      id: "ref-rename-2",
      mode: "refactor",
      prompt: "Change the function name to 'fetchUsers'",
      initialContent: "function getData() {",
      cursorPos: 9,
      expectedContent: "function fetchUsers() {",
      expectedCursorPos: 19,
      expectedCommand: "ciwfetchUsers",
      tags: ["refactor", "rename"],
      difficulty: 1,
    },
    {
      id: "ref-swap-chars-1",
      mode: "refactor",
      prompt: "Fix the typo: swap the two characters to spell 'the'",
      initialContent: "teh quick brown fox",
      cursorPos: 1,
      expectedContent: "the quick brown fox",
      expectedCursorPos: 2,
      expectedCommand: "xp",
      tags: ["refactor", "swap"],
      difficulty: 1,
    },
    {
      // "aer" → "are": cursor on 'e' (pos 1), x deletes 'e' → "ar", p pastes 'e' after 'r' → "are"
      id: "ref-swap-chars-2",
      mode: "refactor",
      prompt: "Fix the typo: swap the two characters to spell 'are'",
      initialContent: "they aer here",
      cursorPos: 6,
      expectedContent: "they are here",
      expectedCursorPos: 7,
      expectedCommand: "xp",
      tags: ["refactor", "swap"],
      difficulty: 1,
    },
    {
      id: "ref-delete-line",
      mode: "refactor",
      prompt: "Delete the entire comment line",
      initialContent: "const x = 1;\n// TODO: remove\nconst y = 2;",
      cursorPos: 13,
      expectedContent: "const x = 1;\nconst y = 2;",
      expectedCursorPos: 13,
      expectedCommand: "dd",
      tags: ["refactor", "delete-line"],
      difficulty: 1,
    },
    {
      id: "ref-change-arg",
      mode: "refactor",
      prompt: "Change the first argument to 'users'",
      initialContent: "getData(items, config)",
      cursorPos: 8,
      expectedContent: "getData(users, config)",
      expectedCursorPos: 13,
      expectedCommand: "ciwusers",
      tags: ["refactor", "rename"],
      difficulty: 1,
    },
    {
      id: "ref-var-to-const",
      mode: "refactor",
      prompt: "Change 'var' to 'const'",
      initialContent: "var x = 1;",
      cursorPos: 0,
      expectedContent: "const x = 1;",
      expectedCursorPos: 5,
      expectedCommand: "cwconst",
      alternativeCommands: ["ciwconst"],
      tags: ["refactor", "rename"],
      difficulty: 1,
    },
    {
      id: "ref-let-to-const",
      mode: "refactor",
      prompt: "Change 'let' to 'const'",
      initialContent: "let count = 0;",
      cursorPos: 0,
      expectedContent: "const count = 0;",
      expectedCursorPos: 5,
      expectedCommand: "cwconst",
      alternativeCommands: ["ciwconst"],
      tags: ["refactor", "rename"],
      difficulty: 1,
    },
  ],
};
