import type { ChallengeSet } from "../types";

export const yankSet: ChallengeSet = {
  mode: "y",
  label: "Yank",
  description: "Practice the y operator — yank text and paste it somewhere",
  key: "y",
  challenges: [
    {
      id: "y-yyp-1",
      mode: "y",
      prompt: "Yank this line and paste it below",
      initialContent: "duplicate me\nsecond line",
      cursorPos: 0,
      expectedContent: "duplicate me\nduplicate me\nsecond line",
      expectedCursorPos: 13,
      expectedCommand: "yyp",
      tags: ["yank", "line", "paste"],
      difficulty: 1,
    },
    {
      id: "y-yyP-1",
      mode: "y",
      prompt: "Yank this line and paste it above",
      initialContent: "first line\ncopy me\nthird line",
      cursorPos: 11,
      expectedContent: "first line\ncopy me\ncopy me\nthird line",
      expectedCursorPos: 11,
      expectedCommand: "yyP",
      tags: ["yank", "line", "paste-above"],
      difficulty: 1,
    },
    {
      id: "y-yyp-2",
      mode: "y",
      prompt: "Yank the second line and paste it below",
      initialContent: "first\nsecond\nthird",
      cursorPos: 6,
      expectedContent: "first\nsecond\nsecond\nthird",
      expectedCursorPos: 13,
      expectedCommand: "yyp",
      tags: ["yank", "line", "paste"],
      difficulty: 1,
    },
    {
      id: "y-yy2p-1",
      mode: "y",
      prompt: "Yank this line and paste it twice below",
      initialContent: "repeat me\nend",
      cursorPos: 0,
      expectedContent: "repeat me\nrepeat me\nrepeat me\nend",
      expectedCursorPos: 20,
      expectedCommand: "yy2p",
      tags: ["yank", "line", "count", "paste"],
      difficulty: 2,
    },
    {
      id: "y-yyjp-1",
      mode: "y",
      prompt: "Yank the first line, move down, and paste it after the second line",
      initialContent: "header\nbody\nfooter",
      cursorPos: 0,
      expectedContent: "header\nbody\nheader\nfooter",
      expectedCursorPos: 13,
      expectedCommand: "yyjp",
      tags: ["yank", "line", "navigate", "paste"],
      difficulty: 2,
    },
    {
      id: "y-yyGp-1",
      mode: "y",
      prompt: "Yank the first line and paste it at the very end",
      initialContent: "move me\nalpha\nbeta",
      cursorPos: 0,
      expectedContent: "move me\nalpha\nbeta\nmove me",
      expectedCursorPos: 19,
      expectedCommand: "yyGp",
      tags: ["yank", "line", "navigate", "paste"],
      difficulty: 2,
    },
    {
      id: "y-yyggP-1",
      mode: "y",
      prompt: "Yank this line and paste it at the very top",
      initialContent: "first\nsecond\nthird",
      cursorPos: 13,
      expectedContent: "third\nfirst\nsecond\nthird",
      expectedCursorPos: 0,
      expectedCommand: "yyggP",
      tags: ["yank", "line", "navigate", "paste"],
      difficulty: 2,
    },
    {
      id: "y-yy3p-1",
      mode: "y",
      prompt: "Yank this line and paste it three times below",
      initialContent: "ha\nend",
      cursorPos: 0,
      expectedContent: "ha\nha\nha\nha\nend",
      expectedCursorPos: 9,
      expectedCommand: "yy3p",
      tags: ["yank", "line", "count", "paste"],
      difficulty: 2,
    },
  ],
};
