import type { ChallengeSet } from "../types";

export const yankSet: ChallengeSet = {
  mode: "y",
  label: "Yank",
  description: "Practice the y operator — yank (copy) text without changing the buffer",
  key: "y",
  challenges: [
    {
      id: "y-yw-1",
      mode: "y",
      prompt: "Yank the word under the cursor (cursor returns to start)",
      initialContent: "copy this word please",
      cursorPos: 5,
      expectedContent: "copy this word please",
      expectedCursorPos: 5,
      expectedCommand: "yw",
      tags: ["yank", "word"],
      difficulty: 1,
    },
    {
      id: "y-yiw-1",
      mode: "y",
      prompt: "Yank the inner word under the cursor",
      initialContent: "select middle word",
      cursorPos: 9,
      expectedContent: "select middle word",
      expectedCursorPos: 7,
      expectedCommand: "yiw",
      tags: ["yank", "inner-word"],
      difficulty: 1,
    },
    {
      id: "y-yy-1",
      mode: "y",
      prompt: "Yank the entire line",
      initialContent: "first line\nsecond line\nthird line",
      cursorPos: 11,
      expectedContent: "first line\nsecond line\nthird line",
      expectedCursorPos: 11,
      expectedCommand: "yy",
      alternativeCommands: ["Y"],
      tags: ["yank", "line"],
      difficulty: 1,
    },
    {
      id: "y-y$-1",
      mode: "y",
      prompt: "Yank from cursor to end of line",
      initialContent: "keep yanking to the end",
      cursorPos: 5,
      expectedContent: "keep yanking to the end",
      expectedCursorPos: 5,
      expectedCommand: "y$",
      tags: ["yank", "end-of-line"],
      difficulty: 1,
    },
    {
      id: "y-yi-quote-1",
      mode: "y",
      prompt: "Yank the text inside the double quotes",
      initialContent: 'const s = "hello";',
      cursorPos: 13,
      expectedContent: 'const s = "hello";',
      expectedCursorPos: 11,
      expectedCommand: 'yi"',
      tags: ["yank", "inner-quotes"],
      difficulty: 2,
    },
    {
      id: "y-yi-paren-1",
      mode: "y",
      prompt: "Yank the text inside the parentheses",
      initialContent: "call(a, b, c);",
      cursorPos: 6,
      expectedContent: "call(a, b, c);",
      expectedCursorPos: 5,
      expectedCommand: "yi(",
      alternativeCommands: ["yi)"],
      tags: ["yank", "inner-paren"],
      difficulty: 2,
    },
    {
      id: "y-y2w-1",
      mode: "y",
      prompt: "Yank the next 2 words",
      initialContent: "alpha beta gamma delta",
      cursorPos: 0,
      expectedContent: "alpha beta gamma delta",
      expectedCursorPos: 0,
      expectedCommand: "y2w",
      tags: ["yank", "count", "word"],
      difficulty: 2,
    },
    {
      id: "y-yaw-1",
      mode: "y",
      prompt: "Yank the word including surrounding space",
      initialContent: "one two three",
      cursorPos: 5,
      expectedContent: "one two three",
      expectedCursorPos: 4,
      expectedCommand: "yaw",
      tags: ["yank", "around-word"],
      difficulty: 2,
    },
  ],
};
